# Generated by Django 3.2.9 on 2021-12-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='welcomeMessage',
            new_name='welcome_message',
        ),
    ]
